sudo: required
addons:
  apt:
    update: true
    packages:
    - docker-ce
services:
- docker
script:
- export DOCKER_CLI_EXPERIMENTAL=enabled
- source utils.sh
- nextcloud_arm_sha=$(get_manifest_sha "nextcloud:latest" "arm" "v7")
- echo $nextcloud_arm_sha
- treehouses_nextcloud_arm_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm")
- echo $treehouses_nextcloud_arm_sha
- flag_arm=$(is_base "nextcloud@"$nextcloud_arm_sha "treehouses/nextcloud@"$treehouses_nextcloud_arm_sha)
- echo $flag_arm
- nextcloud_amd64_sha=$(get_manifest_sha "nextcloud:latest" "amd64")
- echo $nextcloud_amd64_sha
- treehouses_nextcloud_amd64_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "amd64")
- echo $treehouses_nextcloud_amd64_sha
- flag_amd64=$(is_base "nextcloud@"$nextcloud_amd64_sha "treehouses/nextcloud@"$treehouses_nextcloud_amd64_sha)
- echo $flag_amd64
- nextcloud_arm64_sha=$(get_manifest_sha "nextcloud:latest" "arm64")
- echo $nextcloud_arm64_sha
- treehouses_nextcloud__arm64_sha=$(get_manifest_sha "treehouses/nextcloud:latest" "arm64")
- echo $treehouses_nextcloud__arm64_sha
- flag_arm64=$(is_base "nextcloud@"$nextcloud_arm64_sha "treehouses/nextcloud@"$treehouses_nextcloud__arm64_sha)
- echo $flag_arm64
- echo $DOCKERAPIKEY | docker login -u "sevenseas" --password-stdin
- flag=$(compare "nextcloud@"$nextcloud_arm_sha "treehouses/nextcloud@"$treehouses_nextcloud_arm_sha "nextcloud@"$nextcloud_amd64_sha "treehouses/nextcloud@"$treehouses_nextcloud_amd64_sha "nextcloud@"$nextcloud_arm64_sha "treehouses/nextcloud@"$treehouses_nextcloud__arm64_sha)
- echo $flag
  #- flag="true"
before_deploy:
- deploy_image "treehouses/nextcloud" arm
- deploy_image "treehouses/nextcloud" amd64
- deploy_image "treehouses/nextcloud" arm64
- timetag=$(date +%Y%m%d%H%M)
- echo $timetag
- tag1="latest"
- tag2=$timetag
- echo $tag2
- create_manifest treehouses/nextcloud $tag1 $tag2 treehouses/nextcloud-tags:amd64 treehouses/nextcloud-tags:arm
  treehouses/nextcloud-tags:arm64
- docker manifest inspect treehouses/nextcloud:$tag1
- docker manifest inspect treehouses/nextcloud:$tag2
deploy:
- provider: script
  script: docker manifest push treehouses/nextcloud:$tag1; docker manifest push treehouses/nextcloud:$tag2
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$flag = true"
env:
  global:
    - secure: CxZjHRNwdrtn7CBQgNtRNbl6NhvsUGLc1QGV6bxOb/mpil/36gsOLG5OD9A5FWfYKW+1yZ+02idx2FiUcBDZe8kfxSNJibsgoRKRlAJ2Z0ADU//RvSjlK9qMIz8lAVJG9Qr8+xa1qxj3ORmRSvhnWwUekCK02SGqc5x4EsY3m2MPCSQpOSuKzuVX2M6Mmg1AfXM4i03iUrPKNOq9j5CjbFdWWvSKs2wgPkUYEppzUyepSkcU3HqVVQ9sjmHTqUJrkLmlsHI5JNJBjaoyNeeozQ35hM0wMYYraCWDiEsdVdtL4TTWeThC/j9hPznw1ewOhFWt8PzQowiYSLTEyKFV4QP2Pfs9VPtLOYhvChCntzcCnwYwXzuCGwD7hoaID+5xFa0cUL+KOYVZ7tOZREbfSrxqeHzwhDdQUMDu/KTGumjYIH3hnrvHGXKUDRsT65MeWlJPMMIxnrccEOO5pYwu7CII2MbceETDqLBU+7+eli+9U/Tym/92d6n/4M1ifYqi6jSox4mGmiBPGugFuI7RKfrRZPPEoCaKZeP25yRIP2qhAf03mum6Enilp4Mx7+USa2sVtQZEGtDDUy+yI3E7+IB0VmXGKppCwHjbac6ShDVapzjIOMMThsLC2TUmrpNn32FLIw5yCuZ8tykMS27XVNsYGoYu7j+yz7d7SYcQ+Yo=
      #- secure: H4QlpeMCkgJZMoX4jBJ9qZ68V62Upl4T+/lref6iCKvHbTctKRwCUmJt6IoouNuVW/0P752y5bKHl/mAKff4t15gZEndJ5+UWIIbH82dCOFvlBLvqd163bzeia65morfGvl5Nq3Nfe42uFMuWi8RU7YldmPfL0tiBDGjYQgyTmWk4FV283IrwMz/zqRPRayoOti/L8Z8ssJwJf2HcubdDWN/zHfyXc6mmkt7DSYc+dKB6jDmi6smROiWK5w78Uq5lXf+/xgYjX2CPT4p5+udz+5iqbsZQ6jgfspYB2GF4tqMzwgQnB1HPD7amRz2pV3BzX3ZqLbCskRPHbOahjmXcu/V8CYDNBK1H6OhyZS4bCcw4oAFLTJLvWhhfOxco0b1gnzXZkrZKySORXknJptQyWAcMqxFoFoSUBmfOgK/FjfKaD672OiYCDTch9ggDcX23gM2ECCa0nmfJeluEya2a67gSz3VWslqXtW99xl0i+VBjKeB0toabwbSeE/eJi8iWQVAoUeWMZf8w+tYy1C4Bla1L4z3kfcbHSfYP6UJ00+NX9ePPhBSUnQz3vSuzqSYxRTxZ1fiI/5VeJ92KrzQWm9USYDpBNFiTucyGc/dhK0zG7S1+4VsBdaxIXD5KnIGKbnwF8j3c3pDEn8LAipX4dLVChpWuXIQfQTph1OGnQ0=
